version: "3.8"
services: 
     backend:
        build:
          context: .
          dockerfile: Dockerfile
       
        ports: 
          - "81:81"
        networks: 
          - test_network 

networks: 
    test_network:
        driver: bridge